app/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from app import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("kitchen.urls"), name="kitchen"),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kitchen/urls.py
from django.urls import path

from kitchen.views import (
    index,
    CookDetailView,
    CookListView,
    CookCreateView,
    CookInfoUpdateView,
    CookDeleteView,
    DishListView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    DishDetailView,
    DishTypeListView,
    DishTypeCreateView,
    DishTypeDeleteView,
    DishTypeUpdateView,
    DishTypeDetailView,
)

urlpatterns = [
    path("", index, name="index"),
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path("cooks/<int:pk>/update/", CookInfoUpdateView.as_view(), name="cook-update"), # noqa
    path("cooks/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"), # noqa

    path("dish-types/", DishTypeListView.as_view(), name="dish-type-list"),
    path("dish-types/<int:pk>/", DishTypeDetailView.as_view(), name="dish-type-detail"), # noqa
    path("dish-types/create/", DishTypeCreateView.as_view(), name="dish-type-create"), # noqa
    path("dish-types/<int:pk>/update/", DishTypeUpdateView.as_view(), name="dish-type-update"), # noqa
    path("dish-types/<int:pk>/delete/", DishTypeDeleteView.as_view(), name="dish-type-delete"), # noqa

    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path("dishes/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"), # noqa
    path("dishes/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"), # noqa
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
]

app_name = "kitchen"

kitchen/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class DishType(models.Model):
    name = models.CharField(max_length=63)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(blank=True, null=True)

    class Meta:
        verbose_name = "Cook"
        verbose_name_plural = "Cooks"

    def def_absolute_url(self):
        return reverse("kitchen:cook-detail", args=[str(self.id)])

    def __str__(self):
        return f"{self.username} {self.first_name} {self.last_name}"


class Dish(models.Model):
    name = models.CharField(max_length=63)
    description = models.TextField(max_length=1024)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    dish_type = models.ForeignKey(
        DishType, on_delete=models.CASCADE, related_name="dishes"
    )
    cooks = models.ManyToManyField(Cook, related_name="dishes")

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name} ({self.dish_type}) : {self.price}"

kitchen/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms

from kitchen.models import Cook, Dish


class CookCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "years_of_experience",
        )


class CookInfoUpdateForm(forms.ModelForm):
    class Meta:
        model = Cook
        fields = ["first_name", "last_name", "years_of_experience", "is_staff"]

    def clean_license_number(self):
        return self.cleaned_data[
            "first_name", "last_name", "years_of_experience", "is_staff"
        ]


class DishForm(forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    class Meta:

        model = Dish
        fields = "__all__"


class DishTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=63,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search"}),
    )

kitchen/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import QuerySet
from django.shortcuts import render
from django.views import generic
from rest_framework.reverse import reverse_lazy

from kitchen.forms import (
    CookCreationForm,
    DishTypeSearchForm,
    DishForm,
    CookInfoUpdateForm,
)
from kitchen.models import Cook, Dish, DishType


@login_required
def index(request):
    num_cooks = Cook.objects.count()
    num_dishes = Dish.objects.count()
    num_dish_types = DishType.objects.count()

    context = {
        "num_cooks": num_cooks,
        "num_dishes": num_dishes,
        "num_dish_types": num_dish_types,
    }

    return render(request, "kitchen/index.html", context=context)


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    template_name = "kitchen/dish_type_list.html"
    context_object_name = "dish_type_list"
    paginate_by = 8

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishTypeListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = DishTypeSearchForm(initial={"name": name})

        return context

    def get_queryset(self) -> QuerySet:
        queryset = DishType.objects.all()
        name = self.request.GET.get("name")

        if name:
            return queryset.filter(name__icontains=name)
        return queryset


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    fields = "__all__"
    template_name = "kitchen/dish_type_form.html"
    success_url = reverse_lazy("kitchen:dish-type-list")


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    fields = "__all__"
    template_name = "kitchen/dish_type_form.html"
    success_url = reverse_lazy("kitchen:dish-type-list")


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    form_class = DishForm
    template_name = "kitchen/dish_type_confirm_delete.html"
    success_url = reverse_lazy("kitchen:dish-type-list")


class DishTypeDetailView(LoginRequiredMixin, generic.DetailView):
    model = DishType
    template_name = "kitchen/dishtype_detail.html"


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    paginate_by = 5


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("kitchen:dish-list")


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    form_class = DishForm
    template_name = "kitchen/dish_form.html"
    success_url = reverse_lazy("kitchen:dish-list")


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    fields = "__all__"
    template_name = "kitchen/dish_confirm_delete.html"
    success_url = reverse_lazy("kitchen:dish-list")


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    form_class = CookCreationForm
    success_url = reverse_lazy("kitchen:cook-list")


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    queryset = Cook.objects.all()
    paginate_by = 5


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("kitchen:cook-list")


class CookInfoUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    form_class = CookInfoUpdateForm
    success_url = reverse_lazy("kitchen:cook-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>Kitchen</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <title>Kitchen</title>
  <link rel="icon"  href="{% static 'taxi/img/savory.jpg' %}"/>
</head>

<body>
  <header>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Best Kitchen</a>
      <button class="navbar-toggler" type="button"
              data-toggle="collapse" data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent" aria-expanded="false"
              aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">

        <div class="nav-item">
          <a class="nav-link" href="{% url 'kitchen:index' %}">Home page</a>
        </div>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <div>
          {% if user.is_authenticated %}
          User: {{ user.username }}
          <a href="{% url 'logout' %}" class="btn btn-secondary" role="btn" >Logout</a>
        </div>
        <div>
          {%  else %}
          <a href="{% url 'login' %}" class="btn btn-secondary" role="btn">Login</a>
          {% endif %}
        </div>
      </form>
      </div>
    </nav>
    </div>
  </header>
  <div class="container">
    <div class="jumbotron">
      <div class="center-block">
        <img src="/static/kitchen/img/assortment-fresh-organic-fruits-vegetables-rainbow-colors-panoramic-food-background-171245196.jpg"
            class="img-fluid" alt="Responsive image" >
        <br>
      </div>
    </div>
  </div>




<div class="container">

    <div class="col inner-row" style="background-color: #f5f5f5;">
      <div class="d-flex justify-content-around">
        <div ><a href="{% url 'kitchen:cook-list' %}"><h3>Cooks</h3></a></div>
        <div ><a href="{% url 'kitchen:dish-list' %}"><h3>Dishes</h3></a></div>
        <div ><a href="{% url 'kitchen:dish-type-list' %}"><h3>DishTypes</h3></a></div>
      </div>

      {% block content %}{% endblock %}

      {% block pagination %}
          {% include "includes/pagination.html" %}
      {% endblock %}


    </div>

  </div>

</body>

</html>

templates/includes/pagination.html

{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/kitchen/cook_confirm_delete.html
{% extends "base.html" %}

{%  block content %}
    <h1>Delete</h1>
    <p>Are you sure you want to delete the cook  :{{ cook }}</p>

    <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger">

    </form>

{% endblock %}

templates/kitchen/cook_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Username: {{ cook.username }}
    <a href="{% url 'kitchen:cook-delete' pk=cook.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'kitchen:cook-update' pk=cook.id  %}" class="btn btn-secondary link-to-page">
      Update info
    </a>
  </h1>

  <p><strong>First name:</strong> {{ cook.first_name }}</p>
  <p><strong>Last name:</strong> {{ cook.last_name }}</p>
  <p><strong>years_of_experience:</strong> {{ cook.years_of_experience }}</p>
  <p><strong>Is staff:</strong> {{ cook.is_staff }}</p>

  <div class="ml-3">
    <h4>Dishes</h4>

    {% for dish in cook.dishes.all %}
        <hr>
        <p><strong>Name:</strong> {{ dish.name }}</p>
        <p><strong>Dish Type:</strong> {{ dish.dish_type.name }}</p>
        <p class="text-muted"><strong>Id:</strong> {{dish.id}}</p>

    {% empty %}
      <p>No dishes!</p>
    {% endfor %}
  </div>
{% endblock %}

templates/kitchen/cook_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update, Create" }} Cook</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/kitchen/cook_list.html
{% extends "base.html" %}

{% block content %}
  <a style="float: right" href="{% url 'kitchen:cook-create' %}"><h3>Add cook</h3></a>
  <h1 style="text-align: center">Cook List

    </h1>


    {% if cook_list %}
    <table class="table table-hover">
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Years of experience</th>
      </tr>
    {% for cook in cook_list %}
      <tr>
        <td>{{ cook.id }}</td>
        <td><a href="{% url "kitchen:cook-detail" pk=cook.id %}">{{ cook.username }} {% if user == cook %} (Me){% endif %}</a></td>
        <td>{{ cook.first_name }}</td>
        <td>{{ cook.last_name }}</td>
        <td>{{ cook.years_of_experience }}</td>
      </tr>
    {% endfor %}

    </table>
    {% else %}
      <p>There are no cook in the kitchen.</p>
    {% endif %}
{% endblock %}

templates/kitchen/dish_confirm_delete.html
{% extends "base.html" %}

{%  block content %}
    <h1>Delete Dish</h1>
    <p>Are you sure you want to delete the dish  :{{ dish }}</p>

    <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger">

    </form>

{% endblock %}

templates/kitchen/dish_detail.html
{% extends "base.html" %}

{% block content %}
  <p>Dish Type: ({{ dish.dish_type.name }})</p>
  <h3><a style="float: right" href="{% url 'kitchen:dish-update' pk=dish.id %}">Edit</a></h3>
  <h1>Dish: {{ dish.name }}</h1>
  <h4>Cooks</h4>
  <hr>
  <ul>
  {% for cook in dish.cooks.all %}
    <li>{{ cook.first_name }} {{ cook.last_name }}
      ({{ cook.username }})</li>
  {% endfor %}
  </ul>
{% endblock %}

templates/kitchen/dish_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update, Create" }}  Dish</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/kitchen/dish_list.html
{% extends "base.html" %}

{% block content %}
  <a style="float: right"  href="{%  url 'kitchen:dish-create' %}"><h3>Create</h3></a>
  <h1 style="text-align: center">Dish list
  </h1>

  <form action="" method="get">
  {{ search_form.as_p }}
  </form>
  {% if dish_list %}
      <table class="table table-hover">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
        {% for dish in dish_list %}
            <tr>
                <td>
                    {{dish.id }}
                </td>
                <td>
                    <a href="{% url "kitchen:dish-detail" pk=dish.id %}">{{ dish.name }}</a>
                </td>
                <td>
                    <a href="{% url "kitchen:dish-update" pk=dish.id %}">UPDATE</a>
                </td>
                <td>
                    <a href="{% url "kitchen:dish-delete" pk=dish.id %}">DELETE</a>
                </td>
            </tr>
        {% endfor %}
      </table>

  {% else %}
    <p>There are no dishes in the kitchen</p>
  {% endif %}
{% endblock %}

templates/kitchen/dish_type_confirm_delete.html
{% extends "base.html" %}

{%  block content %}
    <h1>Delete Dish Type</h1>
    <p>Are you sure you want to delete the dish type :{{ dishtype }}</p>
    <p><i>All Dishes with Dish type  will be also deleted!!!</i></p>

    <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger">

    </form>

{% endblock %}

templates/kitchen/dish_type_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update, Create" }}  Dish Type</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/kitchen/dish_type_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block sidebar %}
        {% include "includes/sidebar.html" %}
{% endblock %}
{% block content %}
    <h1>Dish Types List
    <a style="float: right" href="{% url 'kitchen:dish-type-create' %}">
      <h3>Create type</h3>
    </a>
    </h1>

    <form action="" method="get" class="form-inline">
      {{ search_form|crispy }}
    <input class="btn btn-primary" type="submit" value="Search">
    </form>
    {% if dish_type_list %}
      <ul>
      {% for dish_type in dish_type_list %}
        <a  href="{% url 'kitchen:dish-type-detail' pk=dish_type.id %}"><li>{{ dish_type.name}}</li></a>
      {% endfor %}
      </ul>
    {% else %}
      <p>There are no Dish Types in the Kitchen</p>
    {% endif %}

{% endblock %}

templates/kitchen/dishtype_detail.html
{% extends "base.html" %}



{% block content %}
  <p>Dish Type: ({{ dishtype.name }})</p>

  <h1>{{ dishtype.name }}</h1>
  <h4>Dishes</h4>
  <hr>
  <ul>
  {% for dish in dishtype.dishes.all %}
    <a  href="{% url 'kitchen:dish-detail' pk=dish.id %}" ><li>{{ dish.name }}</li></a>
  {% endfor %}
  </ul>
{% endblock %}

templates/kitchen/index.html
{% extends "base.html" %}

{% block content %}
  <div class="col text-center">
    <h2>Welcome to the Best Kitchen!</h2>
   </div>
  <p>
    Delicious food is a pleasure that should not be refused.
    Receiving pleasant emotions in your favorite restaurant is also a special
    kind of pleasure.</p>
  <p>The best dishes for you:</p>
  <ul>
    <li><strong>Dishes:</strong> {{ num_dishes }}</li>
    <li><strong>Cooks:</strong> {{ num_cooks }}</li>
    <li><strong>DishType:</strong> {{ num_dish_types }}</li>
  </ul>

{% endblock%}